server:  port: 8081spring:  application:    name: department-service  config:    import: "optional:configserver:http://localhost:8088"
logging:  pattern:    level: "%5p [%X{traceId},%X{spanId}] %m%n"
      